### ISSUE TITLE
Убрать фиксированную высоту

### ISSUE THREAD

**Issue by igosheva** [Yonmay/afrodita#2]
https://github.com/Yonmay/afrodita/blob/5f65f2478bc9ecaaa0ed8f12e947f29d5e9344a9/style.css#L58

**Comment by Yonmay** [comment]
если уберу высоту то блок не по макету закрасится, по примеру сайта который верстали на вебинарах задавал высоту
```
 .footer {
    height: 80px;
    background: #2b2b2b;
    color: #fff;
}(это с примера кода страницы Владимира)
```

Как сделать высоту не фиксированную?
